export type QueryView = "single" | "split" | "swipe" | "globe" | "3d";
export interface ModuleQueryState {
  aoiId?: number; aoiSource?: string; aoiName?: string; aoiGeoJson?: string; fieldId?: number; fieldName?: string;
  provider?: string; satellite?: string; dataset?: string; sensor?: string; index?: string; analysis?: string;
  year?: number; yearFrom?: number; yearTo?: number; monthFrom?: number; monthTo?: number; startDate?: string; endDate?: string;
  cloudThreshold?: number; cloudMask?: string; dwProbabilityThreshold?: number; scale?: number; activeLayer?: string; compareLayer?: string; sceneId?: string; preSceneId?: string; postSceneId?: string; activeScene?: string;
  changeMode?: string; view?: QueryView; orientation?: "vertical" | "horizontal"; slider?: number; opacity?: number; basemap?: string; showAoi?: boolean; showField?: boolean; showLegend?: boolean; showMetadata?: boolean;
  globeHeight?: number; globeRoll?: number; showTerrain?: boolean; showBuildings?: boolean; showLabels?: boolean; showRoads?: boolean; showUserLocation?: boolean; followUserLocation?: boolean; terrainExaggeration?: number;
  globeLat?: number; globeLng?: number; globeZoom?: number; globeHeading?: number; globePitch?: number;
  enhance?: boolean; enhanceModel?: string; enhanceScale?: number; enhanceBackend?: string; showOriginal?: boolean;
}
const n=(v:string|null,min?:number,max?:number)=>{if(!v)return undefined;const x=Number(v);return Number.isFinite(x)&&(min===undefined||x>=min)&&(max===undefined||x<=max)?x:undefined};
const b=(v:string|null)=>v==null?undefined:v==="true"||v==="1";
export function parseModuleQuery(search:string):ModuleQueryState{const q=new URLSearchParams(search);const view=q.get("view");return {aoiId:n(q.get("aoi_id"),1),aoiSource:q.get("aoi_source")||undefined,aoiName:q.get("aoi_name")||undefined,aoiGeoJson:q.get("aoi_geojson")||undefined,fieldId:n(q.get("field_id"),1),fieldName:q.get("field_name")||undefined,provider:q.get("provider")||undefined,satellite:q.get("satellite")||undefined,dataset:q.get("dataset")||undefined,sensor:q.get("sensor")||undefined,index:q.get("index")?.toLowerCase(),analysis:q.get("analysis")||undefined,year:n(q.get("year"),1900,2200),yearFrom:n(q.get("year_from")||q.get("start_year"),1900,2200),yearTo:n(q.get("year_to")||q.get("end_year"),1900,2200),monthFrom:n(q.get("month_from")||q.get("start_month"),1,12),monthTo:n(q.get("month_to")||q.get("end_month"),1,12),startDate:q.get("start_date")||q.get("date_from")||undefined,endDate:q.get("end_date")||q.get("date_to")||undefined,cloudThreshold:n(q.get("cloud")||q.get("cloud_threshold"),0,100),cloudMask:q.get("cloud_mask")||undefined,dwProbabilityThreshold:n(q.get("dw_probability_threshold"),0,1),scale:n(q.get("scale")||q.get("resolution"),0.01),activeLayer:q.get("active_layer")||undefined,compareLayer:q.get("compare_layer")||q.get("compare")||undefined,sceneId:q.get("scene_id")||undefined,preSceneId:q.get("pre_scene_id")||q.get("before_scene_id")||undefined,postSceneId:q.get("post_scene_id")||q.get("after_scene_id")||undefined,activeScene:q.get("active_scene")||undefined,changeMode:q.get("change_mode")||undefined,view:view==="split"||view==="swipe"||view==="globe"||view==="3d"?view:"single",orientation:q.get("orientation")==="horizontal"?"horizontal":"vertical",slider:n(q.get("slider"),0,100),opacity:n(q.get("opacity"),0,1),basemap:q.get("basemap")||undefined,showAoi:b(q.get("show_aoi")),showField:b(q.get("show_field")),showLegend:b(q.get("show_legend")),showMetadata:b(q.get("show_metadata")),globeHeight:n(q.get("globe_height"),20,40000000),globeRoll:n(q.get("globe_roll"),-180,180),showTerrain:b(q.get("show_terrain")),showBuildings:b(q.get("show_buildings")),showLabels:b(q.get("show_labels")),showRoads:b(q.get("show_roads")),showUserLocation:b(q.get("show_user_location")),followUserLocation:b(q.get("follow_user_location")),terrainExaggeration:n(q.get("terrain_exaggeration"),0.5,3),globeLat:n(q.get("globe_lat"),-90,90),globeLng:n(q.get("globe_lng"),-180,180),globeZoom:n(q.get("globe_zoom"),0,24),globeHeading:n(q.get("globe_heading"),-360,360),globePitch:n(q.get("globe_pitch"),-90,85),enhance:b(q.get("enhance")),enhanceModel:q.get("enhance_model")||undefined,enhanceScale:n(q.get("enhance_scale"),1,4),enhanceBackend:q.get("enhance_backend")||undefined,showOriginal:b(q.get("show_original"))};}
export function serializeModuleQuery(s:ModuleQueryState){const q=new URLSearchParams();const p=(k:string,v:unknown)=>{if(v!==undefined&&v!==null&&v!=="")q.set(k,String(v))};Object.entries({aoi_id:s.aoiId,aoi_source:s.aoiSource,aoi_name:s.aoiName,aoi_geojson:s.aoiGeoJson,field_id:s.fieldId,field_name:s.fieldName,provider:s.provider,satellite:s.satellite,dataset:s.dataset,sensor:s.sensor,index:s.index,analysis:s.analysis,year:s.year,year_from:s.yearFrom,year_to:s.yearTo,month_from:s.monthFrom,month_to:s.monthTo,start_date:s.startDate,end_date:s.endDate,cloud:s.cloudThreshold,cloud_mask:s.cloudMask,dw_probability_threshold:s.dwProbabilityThreshold,scale:s.scale,active_layer:s.activeLayer,compare_layer:s.compareLayer,scene_id:s.sceneId,pre_scene_id:s.preSceneId,post_scene_id:s.postSceneId,active_scene:s.activeScene,change_mode:s.changeMode,view:s.view,orientation:s.orientation,slider:s.slider,opacity:s.opacity,basemap:s.basemap,show_aoi:s.showAoi,show_field:s.showField,show_legend:s.showLegend,show_metadata:s.showMetadata,globe_height:s.globeHeight,globe_roll:s.globeRoll,show_terrain:s.showTerrain,show_buildings:s.showBuildings,show_labels:s.showLabels,show_roads:s.showRoads,show_user_location:s.showUserLocation,follow_user_location:s.followUserLocation,terrain_exaggeration:s.terrainExaggeration,globe_lat:s.globeLat,globe_lng:s.globeLng,globe_zoom:s.globeZoom,globe_heading:s.globeHeading,globe_pitch:s.globePitch,enhance:s.enhance,enhance_model:s.enhanceModel,enhance_scale:s.enhanceScale,enhance_backend:s.enhanceBackend,show_original:s.showOriginal}).forEach(([k,v])=>p(k,v));return q;}
export function buildModuleShareUrl(path:string,state:ModuleQueryState){const q=serializeModuleQuery(state);return `${path}${q.toString()?`?${q}`:""}`;}
export function updateModuleUrl(path:string,state:ModuleQueryState){
  if(typeof window === "undefined") return;
  const current = new URLSearchParams(window.location.search);
  const next = serializeModuleQuery(state);
  // Preserve renderer-owned camera/options and unknown module parameters.
  for (const [key,value] of current) {
    if (key.startsWith("globe_") || ["show_terrain", "show_buildings", "show_labels", "show_roads", "show_lighting", "show_user_location", "follow_user_location", "terrain_exaggeration", "basemap"].includes(key) || (key === "view" && ["3d", "globe"].includes(value))) next.set(key,value);
  }
  window.history.replaceState(window.history.state,"",`${path}?${next}`);
}

