import { useState } from "react";
import { Link } from "react-router-dom";
import Navbar from "@/components/layout/Navbar";
import { pluginRegistry } from "@/workflow/plugins";

export default function PluginManagerPage() {
  const [plugins, setPlugins] = useState(pluginRegistry.list());
  return <div className="workflow-page"><Navbar /><main className="plugin-page"><div className="plugin-page-header"><div><Link to="/workflow" className="small text-decoration-none"><i className="bi bi-arrow-left me-1" /> Workflow builder</Link><h1><i className="bi bi-puzzle" /> Plugin manager</h1><p>Capability-based extensions for workflow nodes, imagery, layers, widgets, and exporters.</p></div><span className="badge text-bg-success">API v1</span></div><div className="plugin-grid">{plugins.map((plugin) => <article className="plugin-card" key={plugin.id}><div className="plugin-card-top"><span className="plugin-icon"><i className="bi bi-puzzle-fill" /></span><span className={`status-dot ${plugin.enabled ? "active" : "inactive"}`} /> </div><h2>{plugin.name}</h2><p>{plugin.description}</p><div className="plugin-meta"><span>v{plugin.version}</span><span>{plugin.author}</span></div><div className="plugin-capabilities">{plugin.capabilities.map((capability) => <span key={capability}>{capability}</span>)}</div><div className="plugin-permissions"><small>Permissions</small><div>{plugin.permissions?.length ? plugin.permissions.join(" · ") : "No elevated permissions"}</div></div><button className={`btn btn-sm ${plugin.enabled ? "btn-outline-danger" : "btn-outline-success"}`} onClick={() => { pluginRegistry.toggle(plugin.id, !plugin.enabled); setPlugins(pluginRegistry.list()); }}>{plugin.enabled ? "Disable" : "Enable"}</button>{plugin.lastError && <div className="text-danger small mt-2">{plugin.lastError}</div>}</article>)}</div><div className="plugin-security-note"><i className="bi bi-shield-lock" /><div><strong>Plugin security</strong><p>Plugins never receive session tokens directly. Network, storage, local-files, and backend access are explicit capabilities and remote entries must come from a trusted registry.</p></div></div></main></div>;
}
