import { useEffect, useMemo, useRef, useState } from "react";
import type { AoiFeature } from "@/types/map";
import type { FeatureCollection } from "geojson";
import type { ImageryScene } from "./types";
import { getNasaGibsLayers, runRasterToolbox } from "./api";
import { useI18nStore } from "@/hooks/useI18nStore";
import type { RasterData, RasterOperation, RasterResult, RasterSourceKind } from "./raster/rasterTypes";
import { readRasterFile, readRasterUrl, readSceneAsset } from "./raster/rasterSources";
import { downloadRaster } from "./raster/rasterExport";
import { runRasterOperationAsync } from "./raster/rasterWorkerClient";
import "./raster/raster.css";
import { parseRasterQuery, updateRasterQuery } from "./raster/rasterQueryState";

const NASA_WMTS = "https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/{layer}/default/{time}/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg";
const OVERTURE_RELEASE = "2026-08-19.0";
const operations: Array<[RasterOperation, string]> = [["ndvi", "NDVI"], ["evi", "EVI"], ["ndwi", "NDWI"], ["savi", "SAVI"], ["band_math", "Band math"], ["clip", "Clip"], ["stretch", "Stretch"], ["clip_stretch", "Clip + stretch"], ["reclassify", "Reclassify"], ["histogram", "Histogram"], ["statistics", "Statistics"], ["zonal_statistics", "Zonal statistics"], ["slope", "Slope"], ["aspect", "Aspect"], ["hillshade", "Hillshade"], ["change_detection", "Change detection"]];

function RasterPreview({ result }: { result: RasterResult }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = canvasRef.current; if (!canvas || !result.bands[0]) return;
    const scale = Math.min(1, 640 / Math.max(result.width, result.height)); canvas.width = Math.max(1, Math.round(result.width * scale)); canvas.height = Math.max(1, Math.round(result.height * scale));
    const context = canvas.getContext("2d"); if (!context) return; const image = context.createImageData(canvas.width, canvas.height); const values = result.bands[0]; const min = result.stats?.min ?? Math.min(...values); const max = result.stats?.max ?? Math.max(...values);
    for (let y = 0; y < canvas.height; y++) for (let x = 0; x < canvas.width; x++) { const sourceIndex = Math.min(result.height - 1, Math.floor(y / scale)) * result.width + Math.min(result.width - 1, Math.floor(x / scale)); const value = values[sourceIndex]; const normalized = Number.isFinite(value) ? Math.round(Math.max(0, Math.min(1, (value - min) / (max - min || 1))) * 255) : 0; const pixel = (y * canvas.width + x) * 4; image.data[pixel] = normalized; image.data[pixel + 1] = result.operation === "ndwi" || result.operation === "ndvi" ? Math.min(255, normalized + 35) : normalized; image.data[pixel + 2] = result.operation === "change_detection" ? 255 - normalized : normalized; image.data[pixel + 3] = Number.isFinite(value) ? 255 : 0; }
    context.putImageData(image, 0, 0);
  }, [result]);
  return <canvas ref={canvasRef} className="raster-toolbox-preview" aria-label="Pratinjau raster" />;
}

export default function ImageryToolsPanel({ scene, aoi, assetKey, activeNasaLayerUrl, storyMap, onNasaLayer, onStory }: { scene: ImageryScene | null; aoi: AoiFeature | null; assetKey: string; activeNasaLayerUrl: string | null; storyMap: FeatureCollection | null; onNasaLayer: (url: string | null) => void; onStory: (story: FeatureCollection | null) => void; mapMode?: "flat" | "globe"; onMapMode?: (mode: "flat" | "globe") => void; }) {
  const t = useI18nStore((state) => state.t); const queryState = useMemo(() => parseRasterQuery(typeof window === "undefined" ? "" : window.location.search), []); const [toolsOpen, setToolsOpen] = useState(false); const [sourceKind, setSourceKind] = useState<RasterSourceKind>(queryState.sourceType ?? "file"); const [source, setSource] = useState<RasterData | null>(null); const [afterSource, setAfterSource] = useState<RasterData | null>(null); const [sourceName, setSourceName] = useState(""); const [afterSourceName, setAfterSourceName] = useState(""); const [sourceError, setSourceError] = useState(""); const [cogUrl, setCogUrl] = useState(""); const [operation, setOperation] = useState<RasterOperation>(queryState.operation ?? "ndvi"); const [bands, setBands] = useState({ red: String(queryState.red ?? 4), green: String(queryState.green ?? 3), blue: String(queryState.blue ?? 2), nir: String(queryState.nir ?? 8), swir: String(queryState.swir ?? 11), elevation: "1" }); const [expression, setExpression] = useState(queryState.expression ?? "(NIR - RED) / (NIR + RED)"); const [reclassRules, setReclassRules] = useState("-1,0,1,Rendah\n0,0.5,2,Sedang\n0.5,1,3,Tinggi"); const [result, setResult] = useState<RasterResult | null>(null); const [progress, setProgress] = useState(0); const [progressMessage, setProgressMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [changeMode, setChangeMode] = useState<"difference" | "ratio" | "threshold">((queryState.changeMode as "difference" | "ratio" | "threshold") ?? "difference"); const [threshold, setThreshold] = useState(String(queryState.threshold ?? 0.2)); const abortRef = useRef<AbortController | null>(null);
  const [layers, setLayers] = useState<{ id: string; name: string }[]>([]); const [nasaLayer, setNasaLayer] = useState(""); const [nasaDate, setNasaDate] = useState(new Date().toISOString().slice(0, 10)); const [storyTitle, setStoryTitle] = useState("Cerita Scene Satelit"); const [storyText, setStoryText] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { getNasaGibsLayers().then(response => { setLayers(response.layers); setNasaLayer(response.layers[0]?.id ?? ""); }).catch(() => undefined); }, []);
  useEffect(() => { if (typeof window === "undefined" || !["/satellite-imagery", "/imagery"].includes(window.location.pathname)) return; updateRasterQuery({ operation, sourceType: ["file", "url", "cog", "scene_asset"].includes(sourceKind) ? sourceKind as Exclude<RasterSourceKind, "array"> : undefined, sourceId: sourceKind === "scene_asset" ? scene?.id : undefined, assetKey: sourceKind === "scene_asset" ? assetKey : undefined, expression: operation === "band_math" ? expression : undefined, red: Number(bands.red), green: Number(bands.green), blue: Number(bands.blue), nir: Number(bands.nir), swir: Number(bands.swir), threshold: Number(threshold), changeMode: operation === "change_detection" ? changeMode : undefined, outputType: "preview" }); }, [assetKey, bands, changeMode, expression, operation, scene?.id, sourceKind, threshold]);
  const nasaUrl = useMemo(() => nasaLayer ? NASA_WMTS.replace("{layer}", nasaLayer).replace("{time}", nasaDate) : null, [nasaDate, nasaLayer]); const nasaVisible = Boolean(nasaUrl && activeNasaLayerUrl === nasaUrl);
  const loadSource = async (loader: () => Promise<RasterData>) => { setSourceError(""); setError(""); try { const data = await loader(); setSource(data); setSourceName(data.source?.name ?? data.source?.fileName ?? "Raster"); setMessage(t("raster.sourceReady")); } catch (caught) { setSource(null); setSourceError(t((caught as Error).message)); } };
  const loadAfterSource = async (loader: () => Promise<RasterData>) => { setSourceError(""); try { const data = await loader(); setAfterSource(data); setAfterSourceName(data.source?.name ?? data.source?.fileName ?? "Raster"); } catch (caught) { setAfterSource(null); setSourceError(t((caught as Error).message)); } };
  const bandsParam = Object.fromEntries(Object.entries(bands).map(([key, value]) => [key, Number(value)]).filter(([, value]) => Number.isFinite(Number(value)) && Number(value) > 0));
  const executeLocal = async () => { if (!source) { setError(t("raster.noSource")); return; } if (["clip", "clip_stretch", "zonal_statistics"].includes(operation) && !aoi) { setError(t("raster.noAoi")); return; } if (operation === "change_detection" && !afterSource) { setError(t("raster.beforeAfterRequired")); return; } const rules = reclassRules.split(/\r?\n/).map(line => line.split(",").map(value => value.trim())).filter(values => values.length >= 3 && values.every(Boolean)).map(values => ({ min: Number(values[0]), max: Number(values[1]), value: Number(values[2]), label: values[3] })).filter(rule => Number.isFinite(rule.min) && Number.isFinite(rule.max) && Number.isFinite(rule.value)); setBusy(true); setError(""); setProgress(0); abortRef.current = new AbortController(); try { const localResult = await runRasterOperationAsync(source, { operation, bands: bandsParam, expression, clipGeometry: aoi?.geometry, changeMode, threshold: Number(threshold), reclassRules: rules, hillshadeAzimuth: 315, hillshadeAltitude: 45, saviL: 0.5 }, { signal: abortRef.current.signal, after: afterSource ?? undefined, onProgress: (value, text) => { setProgress(value); setProgressMessage(text); } }); setResult(localResult); setMessage(t("raster.completed")); } catch (caught) { setError(t((caught as Error).message)); } finally { setBusy(false); abortRef.current = null; } };
  const executeServerFallback = async () => { if (!scene || !aoi) return; setBusy(true); setError(""); try { const fallback = await runRasterToolbox({ itemUrl: scene.id, assetKey, aoi, operation, bands: Object.values(bands).join(","), export: false }); setMessage(t("raster.serverFallback")); setResult({ width: 1, height: 1, bands: [new Float32Array([fallback.stats.mean])], nodata: null, stats: { ...fallback.stats, pixelCount: 1, validPixelCount: 1, nodataPixelCount: 0 }, histogram: fallback.histogram, bins: fallback.bins, operation }); } catch { setError(t("raster.sourceUnavailable")); } finally { setBusy(false); } };
  const cancel = () => abortRef.current?.abort(); const toggleStory = () => { if (storyMap) { onStory(null); setMessage("Story Map disembunyikan."); return; } if (!scene || !aoi) return; onStory({ type: "FeatureCollection", features: [{ type: "Feature", geometry: aoi.geometry, properties: { title: storyTitle, narrative: storyText, scene_id: scene.id, acquired_at: scene.acquired_at } }] }); setMessage(t("raster.storyReady")); }; const toggleNasa = () => { if (!nasaUrl) return; onNasaLayer(nasaVisible ? null : nasaUrl); };
  return <div className="mt-3"><button type="button" className="btn btn-success w-100 text-start d-flex justify-content-between align-items-center" aria-expanded={toolsOpen} onClick={() => setToolsOpen(value => !value)}><span><i className="bi bi-tools me-2" />{t("imagery.tools.title")}</span><i className={`bi bi-chevron-${toolsOpen ? "up" : "down"}`} /></button>
    {toolsOpen && <div className="accordion mt-2" id="imageryToolsAccordion"><section className="card mb-3"><div className="card-header py-2"><i className="bi bi-cpu me-1" /> {t("raster.title")}</div><div className="card-body"><p className="small text-muted mb-2">{t("raster.localProcessingDescription")}</p>
      <label className="form-label" htmlFor="raster-source">{t("raster.source")}</label><select id="raster-source" className="form-select form-select-sm mb-2" value={sourceKind} onChange={event => { const next = event.target.value as RasterSourceKind; setSourceKind(next); if (next === "array") setSource(result ? { ...result, source: result.source } : null); else setSource(null); }}><option value="file">{t("raster.sourceFile")}</option><option value="cog">{t("raster.sourceCog")}</option><option value="scene_asset">{t("raster.sourceScene")}</option><option value="array">{t("raster.sourcePrevious")}</option></select>
      {sourceKind === "file" && <input className="form-control form-control-sm" type="file" accept=".tif,.tiff,.geotiff" aria-label={t("raster.sourceFile")} onChange={event => { const file = event.target.files?.[0]; if (file) void loadSource(() => readRasterFile(file)); }} />}{sourceKind === "cog" && <div className="input-group input-group-sm"><input className="form-control" value={cogUrl} onChange={event => setCogUrl(event.target.value)} placeholder="https://…/raster.tif" aria-label={t("raster.sourceCog")} /><button type="button" className="btn btn-outline-secondary" disabled={!cogUrl || busy} onClick={() => void loadSource(() => readRasterUrl(cogUrl, "cog"))}>{t("raster.load")}</button></div>}{sourceKind === "scene_asset" && <button type="button" className="btn btn-sm btn-outline-secondary" disabled={!scene || busy || !scene?.assets?.length} onClick={() => void loadSource(() => readSceneAsset(scene!, assetKey))}>{scene?.assets?.length ? `${t("raster.load")} · ${assetKey}` : t("raster.sceneAssetUnavailable")}</button>}{sourceKind === "array" && <p className="small text-muted mb-0">{result ? t("raster.sourceResultAvailable") : t("raster.noPreviousResult")}</p>}
      {sourceName && <div className="small text-success mt-2" role="status">{sourceName} · {source?.width}×{source?.height} · {source?.bandCount ?? source?.bands.length} band</div>}{sourceError && <div className="alert alert-danger py-2 mt-2 mb-0" role="alert">{sourceError}</div>}
      <div className="row g-2 mt-1"><div className="col-md-6"><label className="form-label" htmlFor="raster-operation">{t("raster.operation")}</label><select id="raster-operation" className="form-select form-select-sm" value={operation} onChange={event => setOperation(event.target.value as RasterOperation)}>{operations.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="col-md-6"><label className="form-label" htmlFor="raster-expression">{t("raster.expression")}</label><input id="raster-expression" className="form-control form-control-sm" value={expression} onChange={event => setExpression(event.target.value)} disabled={operation !== "band_math"} /></div></div>
      <fieldset className="raster-band-grid mt-2"><legend className="form-label">{t("raster.bandMapping")}</legend>{(["red", "green", "blue", "nir", "swir", "elevation"] as const).map(name => <label key={name} className="small">{t(`raster.${name}Band`)}<input className="form-control form-control-sm" inputMode="numeric" value={bands[name]} onChange={event => setBands(current => ({ ...current, [name]: event.target.value }))} /></label>)}</fieldset>
      {operation === "reclassify" && <div className="mt-2"><label className="form-label" htmlFor="raster-reclass-rules">{t("raster.reclassRules")}</label><textarea id="raster-reclass-rules" className="form-control form-control-sm" rows={3} value={reclassRules} onChange={event => setReclassRules(event.target.value)} /><small className="text-muted">min,max,nilai,label</small></div>}
      {operation === "change_detection" && <div className="row g-2 mt-1"><div className="col"><label className="form-label">{t("raster.changeMode")}</label><select className="form-select form-select-sm" value={changeMode} onChange={event => setChangeMode(event.target.value as typeof changeMode)}><option value="difference">Difference</option><option value="ratio">Ratio</option><option value="threshold">Threshold</option></select></div><div className="col"><label className="form-label">{t("raster.threshold")}</label><input className="form-control form-control-sm" type="number" value={threshold} onChange={event => setThreshold(event.target.value)} /></div></div>}
      {operation === "change_detection" && <div className="mt-2"><label className="form-label" htmlFor="raster-after-file">{t("raster.after")}</label><input id="raster-after-file" className="form-control form-control-sm" type="file" accept=".tif,.tiff,.geotiff" onChange={event => { const file = event.target.files?.[0]; if (file) void loadAfterSource(() => readRasterFile(file)); }} /><small className="text-muted">{afterSourceName || t("raster.beforeAfterHint")}</small></div>}
      <div className="d-flex gap-2 mt-3"><button type="button" className="btn btn-primary btn-sm flex-fill" disabled={!source || busy} onClick={() => void executeLocal()}>{busy ? `${t("raster.processing")} ${Math.round(progress)}%` : t("raster.run")}</button>{busy && <button type="button" className="btn btn-outline-danger btn-sm" onClick={cancel}>{t("raster.cancel")}</button>}<button type="button" className="btn btn-outline-secondary btn-sm" disabled={busy || !!source || !scene || !aoi} onClick={() => void executeServerFallback()}>{t("raster.serverFallbackButton")}</button></div>{busy && <div className="progress mt-2" role="progressbar" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><div className="progress-bar" style={{ width: `${progress}%` }}>{progressMessage}</div></div>}{error && <div className="alert alert-danger py-2 mt-2 mb-0" role="alert">{error}</div>}{message && <div className="small text-muted mt-2" role="status">{message}</div>}
      {result && <div className="raster-result mt-3"><div className="d-flex justify-content-between align-items-center"><strong>{t("raster.result")}</strong><div className="btn-group btn-group-sm"><button type="button" className="btn btn-outline-success" onClick={() => downloadRaster(result)}>{t("raster.downloadGeoTiff")}</button><button type="button" className="btn btn-outline-secondary" disabled title={t("raster.cogUnavailable")}>{t("raster.downloadCog")}</button></div></div><RasterPreview result={result} />{result.histogram && <div className="mt-2"><div className="small text-muted mb-1">{t("raster.histogram")}</div><div className="raster-histogram" role="img" aria-label={t("raster.histogram")}>{result.histogram.map((count, index) => <span key={index} title={`${count}`} style={{ height: `${Math.max(2, count / Math.max(...(result.histogram ?? [0])) * 100)}%` }} />)}</div></div>}{result.legend?.length && <div className="small mt-2"><div className="text-muted">{t("raster.legend")}</div>{result.legend.map(rule => <span className="badge text-bg-light me-1" key={`${rule.min}-${rule.max}-${rule.value}`}>{rule.label ?? rule.value}</span>)}</div>}{result.stats && <div className="raster-stats-grid mt-2">{(["min", "max", "mean", "median", "stdDev", "validPixelCount", "nodataPixelCount"] as const).map(key => <div key={key}><span>{t(`raster.${key}`)}</span><strong>{result.stats?.[key] == null ? "-" : Number(result.stats?.[key]).toLocaleString(undefined, { maximumFractionDigits: 4 })}</strong></div>)}</div>}</div>}
    </div></section><section className="card mb-3"><div className="card-header py-2"><i className="bi bi-globe-americas" /> NASA GIBS / Earthdata Time Layer</div><div className="card-body"><div className="row g-2"><div className="col-md-5"><select className="form-select form-select-sm" value={nasaLayer} onChange={event => setNasaLayer(event.target.value)}>{layers.map(layer => <option key={layer.id} value={layer.id}>{layer.name}</option>)}</select></div><div className="col-md-4"><input type="date" className="form-control form-control-sm" value={nasaDate} onChange={event => setNasaDate(event.target.value)} /></div><div className="col-md-3"><button type="button" className={`btn btn-sm w-100 ${nasaVisible ? "btn-primary" : "btn-outline-primary"}`} disabled={!nasaUrl} aria-pressed={nasaVisible} onClick={toggleNasa}>{nasaVisible ? "Sembunyikan" : nasaUrl ? "Tampilkan" : "Pilih layer"}</button></div></div><small className="text-muted d-block mt-2">Layer harian NASA GIBS dapat dibandingkan dengan scene aktif.</small></div></section><section className="card mb-3"><div className="card-header py-2"><i className="bi bi-buildings" /> Overture Maps</div><div className="card-body small">Data Overture tersedia sebagai PMTiles resmi. <a href={`https://pmtiles.io/?url=https://overturemaps-extras-us-west-2.s3.us-west-2.amazonaws.com/tiles/${OVERTURE_RELEASE}/base.pmtiles`} target="_blank" rel="noreferrer">Buka Explorer Overture</a></div></section><section className="card"><div className="card-header py-2"><i className="bi bi-book-half" /> Story Map</div><div className="card-body"><input className="form-control form-control-sm mb-2" value={storyTitle} onChange={event => setStoryTitle(event.target.value)} placeholder="Judul cerita" /><textarea className="form-control form-control-sm mb-2" rows={3} value={storyText} onChange={event => setStoryText(event.target.value)} placeholder="Narasi scene, perubahan, atau temuan..." /><button type="button" className={`btn btn-sm ${storyMap ? "btn-success" : "btn-outline-success"}`} disabled={!storyMap && (!scene || !aoi)} aria-pressed={Boolean(storyMap)} onClick={toggleStory}><i className={`bi ${storyMap ? "bi-eye-slash" : "bi-bookmark-plus"}`} /> {storyMap ? "Sembunyikan Story Map" : "Tambahkan scene ke Story Map"}</button></div></section></div>}
  </div>;
}
