import type { WildfireEvent } from "./types";

const KALIMANTAN_BBOX: [number, number, number, number] = [108.8, -4.6, 119.4, 4.4];

export const FALLBACK_WILDFIRE_EVENTS: WildfireEvent[] = [
  {
    id: "kalimantan-2026",
    slug: "kalimantan-2026",
    title: "Karhutla Kalimantan 2026",
    short_title: "Kalimantan 2026",
    description: "Pemantauan deteksi panas dan sumber data kebakaran hutan dan lahan di Kalimantan.",
    disaster_type: "forest_fire",
    status: "active",
    start_date: "2026-01-01",
    end_date: null,
    monitoring_from: "2026-08-20",
    monitoring_to: null,
    published_at: "2026-08-28T00:00:00Z",
    last_data_at: "2026-08-27T23:59:00Z",
    last_synced_at: "2026-08-28T01:00:00Z",
    year: 2026,
    country_code: "ID",
    province_codes: ["61", "62", "63", "64", "65"],
    city_codes: [],
    provinces: ["Kalimantan Barat", "Kalimantan Tengah", "Kalimantan Selatan", "Kalimantan Timur", "Kalimantan Utara"],
    bbox: KALIMANTAN_BBOX,
    center_lat: -1.7,
    center_lon: 113.4,
    default_zoom: 5,
    thumbnail: "/images/disaster-water-risk.jpg",
    severity: "high",
    source_ids: ["nasa-firms", "laporan-kemenhut"],
    source: "NASA FIRMS · Kementerian Kehutanan",
    boundary_source: "SP3STAB",
    methodology: "Deteksi panas satelit dikurasi sebagai event pemantauan; tidak disamakan dengan incident atau area terbakar.",
    limitations: ["Hotspot adalah indikasi anomali termal dan memerlukan verifikasi lapangan."],
    is_featured: true,
    is_public: true,
    hotspot_count: 6970,
    high_confidence_count: 424,
    burned_area_ha: 29063.54,
    burned_area_source: "Laporan resmi Januari–Juni 2026",
    updated_at: "2026-08-28T01:00:00Z",
  },
  {
    id: "sumatra-2026",
    slug: "sumatra-2026",
    title: "Karhutla Sumatra 2026",
    short_title: "Sumatra 2026",
    description: "Event pemantauan lintas provinsi di Sumatra.",
    disaster_type: "forest_fire",
    status: "monitoring",
    start_date: "2026-02-01",
    end_date: null,
    monitoring_from: "2026-08-01",
    monitoring_to: null,
    published_at: "2026-08-10T00:00:00Z",
    last_data_at: "2026-08-27T23:59:00Z",
    last_synced_at: "2026-08-28T01:00:00Z",
    year: 2026,
    country_code: "ID",
    province_codes: [],
    city_codes: [],
    provinces: ["Riau", "Jambi", "Sumatera Selatan"],
    bbox: [95.0, -5.8, 106.5, 5.9],
    center_lat: -0.5,
    center_lon: 102.5,
    default_zoom: 5,
    thumbnail: "/images/land-change-disturbance.jpg",
    severity: "medium",
    source_ids: ["nasa-firms"],
    source: "NASA FIRMS",
    boundary_source: "SP3STAB",
    methodology: "Deteksi panas berdasarkan sumber sensor yang tersedia.",
    limitations: ["Kelengkapan bergantung pada ketersediaan sumber sensor."],
    is_featured: false,
    is_public: true,
    hotspot_count: 2184,
    high_confidence_count: 168,
    burned_area_ha: null,
    burned_area_source: null,
    updated_at: "2026-08-28T01:00:00Z",
  },
];
